name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  strategy:
    matrix:
      configuration: [Debug, Release]
      platform: [x86, x64]
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE"
        devenv curve-hacker.sln /build "${{configuration}}|${{platform}}"
    - name: Test
      run: |
        $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform"
        vstest.console .build/${{platform}}${{configuration}}/test-*.dll 